# Generated by Django 4.2.1 on 2023-05-21 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentnumber', models.TextField(default='', max_length=20)),
                ('name', models.TextField(default='', max_length=65)),
                ('section', models.TextField(default='', max_length=20)),
                ('department', models.TextField(default='', max_length=20)),
                ('age', models.TextField(default='', max_length=20)),
                ('gender', models.TextField(default='', max_length=20)),
                ('address', models.TextField(default='', max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Absent', 'Absent')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudapp.student')),
            ],
        ),
    ]
