# Generated by Django 4.2.1 on 2023-05-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_student_department_alter_student_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='idnumber',
        ),
    ]
