# Generated by Django 4.2.1 on 2023-05-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_attendance_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='discussion',
            field=models.CharField(default='Lecture', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='room',
            field=models.CharField(default='206', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subjects',
            field=models.CharField(default='CIT511', max_length=10),
        ),
    ]
