# Generated by Django 4.2.1 on 2023-05-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_remove_student_idnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.TextField(default='', max_length=20),
        ),
    ]
