# Generated by Django 4.2.1 on 2023-05-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0006_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='name',
            field=models.TextField(default='', max_length=65),
        ),
        migrations.AddField(
            model_name='attendance',
            name='section',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='studentnumber',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.TextField(default='', max_length=10),
        ),
    ]
