# Generated by Django 4.2.1 on 2023-05-17 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0007_remove_attendance_student_attendance_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='section',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='studentnumber',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crudapp.student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.TextField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.TextField(default='', max_length=20),
        ),
    ]
